module.exports = function(sequelize, Sequelize) {
  return sequelize.define('out_warm', {
    gid: {type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true, field: 'gid'},
    parcelId: {type: Sequelize.STRING, field: 'parcel_id'},
    doy: {type: Sequelize.INTEGER, field: 'doy', allowNull: false},
    year: {type: Sequelize.INTEGER, field: 'year'},
    variety: {type: Sequelize.STRING, field: 'variety'},
    irrigationStrategy: {type: Sequelize.STRING, field: 'irrigation_strategy'},
    soilType: {type: Sequelize.STRING, field: 'soilType'},
    weatherForecast: {type: Sequelize.STRING, field: 'weather_forecast', allowNull: false, defaultValue: false},
    groundBiomass: {type: Sequelize.REAL, field: 'ground_biomass'},
    lai: {type: Sequelize.REAL, field: 'lai'},
    glai: {type: Sequelize.REAL, field: 'glai'},
    lbiomass: {type: Sequelize.REAL, field: 'lbiomass'},
    stemBiomass: {type: Sequelize.REAL, field: 'stem_biomass'},
    orgBiomass: {type: Sequelize.REAL, field: 'org_biomass'},
    height: {type: Sequelize.REAL, field: 'height'},
    stagecode: {type: Sequelize.REAL, field: 'stagecode'},
    transpir: {type: Sequelize.REAL, field: 'transpir'},
    waterUptake: {type: Sequelize.REAL, field: 'water_uptake'},
    waterPercol: {type: Sequelize.REAL, field: 'water_percol'},
    wsIndex: {type: Sequelize.REAL, field: 'ws_index'},
    rootDepth: {type: Sequelize.REAL, field: 'root_depth'},
    waterSoilRooted: {type: Sequelize.REAL, field: 'water_soil_rooted'},
    waterSoilUnrooted: {type: Sequelize.REAL, field: 'water_soil_unrooted'},
    grainAmyl: {type: Sequelize.REAL, field: 'grain_amyl'},
    grainProt: {type: Sequelize.REAL, field: 'grain_prot'},
    grainCrackperc: {type: Sequelize.REAL, field: 'grain_crackperc'},
    stPeakvisc: {type: Sequelize.REAL, field: 'st_peakvisc'},
    stRetrograd: {type: Sequelize.REAL, field: 'st_retrograd'},
    stPasttemp: {type: Sequelize.REAL, field: 'st_pasttemp'},
    chalk: {type: Sequelize.REAL, field: 'chalk'},
    hrYield: {type: Sequelize.REAL, field: 'hr_yield'},
    stGelatintemp: {type: Sequelize.REAL, field: 'st_gelatintemp'},
    stBreakvisc: {type: Sequelize.REAL, field: 'st_breakvisc'},
    grainLipid: {type: Sequelize.REAL, field: 'grain_lipid'},
    disSeverity: {type: Sequelize.REAL, field: 'dis_severity'},
    infections: {type: Sequelize.REAL, field: 'pot_infections'},
    cumInfections: {type: Sequelize.REAL, field: 'cum_infections'},
    disYieldRed: {type: Sequelize.REAL, field: 'dis_yield_red'},
    disgroundBiomassRed: {type: Sequelize.REAL, field: 'disground_biomass_red'},
    disLBiomassRed: {type: Sequelize.REAL, field: 'dis_l_biomass_red'},
    disStBiomassRed: {type: Sequelize.REAL, field: 'dis_st_biomass_red'},
    disLaiRed: {type: Sequelize.REAL, field: 'dis_lai_red'},
    disGlaiRed: {type: Sequelize.REAL, field: 'dis_glai_red'},
    coldSter: {type: Sequelize.REAL, field: 'cold_ster'},
    coldOrgBiomass: {type: Sequelize.REAL, field: 'cold_org_biomass'},
    cumColdster: {type: Sequelize.REAL, field: 'cum_coldster'},
    leachingcum: {type: Sequelize.REAL, field: 'leachingcum'},
    agrochemconc: {type: Sequelize.REAL, field: 'agrochemconc'},
    actgroundBiomass: {type: Sequelize.REAL, field: 'actground_biomass'},
    wlGroundBiomassRed: {type: Sequelize.REAL, field: 'wl_ground_biomass_red'},
    wlLaiRed: {type: Sequelize.REAL, field: 'wl_lai_red'},
    wlGlaiRed: {type: Sequelize.REAL, field: 'wl_glai_red'},
    wlLbiomassRed: {type: Sequelize.REAL, field: 'wl_lbiomass_red'},
    wlStemBiomassRed: {type: Sequelize.REAL, field: 'wl_stem_biomass_red'},
    wlOrgBiomassRed: {type: Sequelize.REAL, field: 'wl_org_biomass_red'},
    actLai: {type: Sequelize.REAL, field: 'act_lai'},
    actGlai: {type: Sequelize.REAL, field: 'act_glai'},
    actLbiomass: {type: Sequelize.REAL, field: 'act_lbiomass'},
    actStemBiomass: {type: Sequelize.REAL, field: 'act_stem_biomass'},
    actOrgBiomass: {type: Sequelize.REAL, field: 'act_org_biomass'},
    forcedGroundBiomass: {type: Sequelize.REAL, field: 'forced_ground_biomass'},
    forcedLai: {type: Sequelize.REAL, field: 'forced_lai'},
    forcedGlai: {type: Sequelize.REAL, field: 'forced_glai'},
    forcedLbiomass: {type: Sequelize.REAL, field: 'forced_lbiomass'},
    forcedStemBiomass: {type: Sequelize.REAL, field: 'forced_stem_biomass'},
    forcedOrgBiomass: {type: Sequelize.REAL, field: 'forced_org_biomass'},
    forcedHeight: {type: Sequelize.REAL, field: 'forced_height'},
    forcedStagecode: {type: Sequelize.REAL, field: 'forced_stagecode'},
    salStress: {type: Sequelize.REAL, field: 'sal_stress'},
    salYieldRed: {type: Sequelize.REAL, field: 'sal_yield_red'},
    salGrbiomRed: {type: Sequelize.REAL, field: 'sal_grbiom_red'},
    salLbiomRed: {type: Sequelize.REAL, field: 'sal_lbiom_red'},
    salStbiomRed: {type: Sequelize.REAL, field: 'sal_stbiom_red'},
    salLaiRed: {type: Sequelize.REAL, field: 'sal_lai_red'},
    salGlaiRed: {type: Sequelize.REAL, field: 'sal_glai_red'},
    stLodging: {type: Sequelize.REAL, field: 'st_lodging'},
    rootLodging: {type: Sequelize.REAL, field: 'root_lodging'}
  }, {
    tableName: 'out_warm'
  });
};